# Generated by Django 5.2.9 on 2025-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='reporter',
            field=models.CharField(default='Exclusive Bulletin', max_length=100),
        ),
    ]
