# Generated by Django 6.0.2 on 2026-02-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_reporter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='news',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
