# Generated by Django 6.0.2 on 2026-06-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherNewsImage',
        ),
    ]
